<?php
/// TODO: TESTE DE TODOSSSSSSS/
// PENDENCIA: TESTE DE PENDENCIA
define("PAULO", "PAULO RICARDO"); // É VISÍVEL EM TODO SCRIPT GLOBAL? RESPOSTA: DESDE QUE AS PÁGINAS QUE FAZEM REFERENCIA COLOQUEM O INCLUDE;
$s = "A CONSTANTE É: " . PAULO;
echo $s;
?>
