<?php
require_once 'principais.php';
/*
 * @AUTOR: PAULO RICARDO
 * 
 * NO MOMENTO DO LOGOUT:
 *
 * 1 - A SESSAO DEVE SER PERSISTIDA PARA ATUALIZAR OS SEGUINTES DADOS DO USUARIO QUE ESTAVA LOGADO:
 *  1.1 ultimoIdiomaSelecionado (MESMO JA TENDO SIDO ATUALIZADO NO LOGIN POIS O USUARIO PODE MUDAR ENQUANTO LOGADO - E MUDADO QUANDO MUDA O IDIOMA
 *                               OU SEJA, JA ESTARA DEFINIDO AQUI)
 *  1.2 ultimoLogout            (A HORA EM QUE FOI FEITO LOGOUT - PRECISA SER DEFINIDO AQUI)
 *  1.3 ultimoIPUtilizado       (O IP PODE MUDAR DURANTE A SESSAO. EX: O USUARIO ESTA DENTRO DE UM AVIAO E MUDA DE AREA)  
 * 
 * 2 - DADOS QUE DEVEM SER DESTRUIDOS / MODIFICADO 
 *  NA SESSAO RAM:
 *  2.1 - O OBJETO USUARIO E EM CONSEQUENCIA O OBJETO SESSAO E DESTRUIDO TAMBEM
 *  2.2 - O ID DA SESSAO PHP DEVE SER TER VALOR 1 (POR CONVECAO)
 *  2.3 - OS DADOS RELATIVOS A AUTENTICACAO SAO DESTRUIDOS $_SESSION[_SESSAO_]
 *  
 *  NO COOKIE DO NAVEGADOR:
 *  2.4 - RETIRAR O COOKIE DE MATER CONECTADO.
 * 
 * 
 * OBSERVACOES:
 * 3 - DESTROE APENAS OS DADOS RELATIVOS AO USUARIO:
 *  3.1 - $_SESSION['Usuario']
 *  3.2 - $_SESSION['_SESSAO_]
 * 
 *
 *
 */

/*E PRECISO QUE SE TESTE PRIMEIRO SE AS VARIAVEIS A SEREM DESTRUIDAS JA FORAM
 * POIS É POSSIVEL QUE O USUARIO CLIQUE DUAS VEZES NO LINK QUE TRAZ PARA ESSA
 * PAGINA E ENTAO O SCRIPT E EXECUTADO DUAS VEZES GERANDO UM ERRO SE NAO FOREM
 * TESTADAS AS VARIAVEIS A SEREM DESTRUIDAS.
 */

if ( isset( $_SESSION['Usuario'] ) && isset( $_SESSION['_SESSAO_'] ) ) //A SESSAO EXISTE E ESTA ABERTA (NAO FOI DESTRUIDA AINDA)
{
    //PERSISTE OS DADOS DA SESSAO ANTES DE DESTRUIR
    //------- PERSITÊNCIA DA SESSAO -------
    $Usuario = unserialize($_SESSION['Usuario']); //RECUPERA OS DADOS DO USUARIO ARMAZENADO NA SESSAO.
    $Usuario->getSessao()->setUltimoLogout( new NBLDateTime(date('Y-m-d H:i:s')) ); //DATA DO LOGOUT  (NO FORMATO EXIGIDO PELO MYSQL PARA TIMESTAMP)
    $Usuario->getSessao()->setUltimoIdiomaSelecionado ( $_SESSION['_IDIOMA_']['idiomaSelecionado'] ); // ARMAZENA O ULTIMO IDIOMA SELECIONADO POIS O USUARIO PODE TER MUDADO DEPOIS DO LOGIN.
    SessaoDAO::persiste($Usuario->getSessao()); //PERSISTE A SESSAO.
    //FIM --- PERSISTENCIA DA SESSAO -------

    //------- DADOS QUE DEVER SER DESTRUIDOS
    unset($_SESSION['_SESSAO_']); 
    unset($_SESSION['Usuario']);
    
    //FIM---- DADOS QUE DEVEM SER DESTRUIDOS
}
//DESTROE O COOKIE QUE ARMAZENA O ID DO USUARIO
setcookie("IUS","", time()-1); 
header("location:index.php");              //REDIRECIONA PARA HOMEPAGE
?>
